syntax on
set number
set cindent
set autoindent
set smartindent
set ruler
set backspace=indent,eol,start
set tabstop=4
set shiftwidth=4
set encoding=utf-8
set termencoding=utf-8
set fileencodings=utf-8,gbk
set hls 
set laststatus=2
set list
set incsearch
set showmatch
set statusline=[%F]%y%r%m%*%=[Line:%l/%L,Column:%c][%p%%]
set listchars=tab:>-,trail:-